# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8df147e72727f8c01f84212098a2e5127cad70c8ebb64b44b27cd43c394ecb67e25ab00bea09fc629fa109195884731007931e2c0bc3011f4fe600b22e7e962

test:
  secret_key_base: 7beabe5c0fd1f45a4e2323cb57685ff5f38397c8dc5d59616d485380da3893896fafd6f938d84b4814ac083f15d501b0933c0e5cd76369df22394ecef804a95d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
